# Generated by Django 5.0.6 on 2024-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_ident', '0003_alter_clientinfo_latitude_alter_clientinfo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
